# Default initial positions for ArmProject's ros2_control fake system

initial_positions:
  base_link_to_motor_1_v4: 0
  motor_1_v4_to_motor_2_v2: 0
  motor_3_v1_2_to_codo_1_modificado_v1: 0
  motor_4_v4_to_motor_5_v1: 0
  motor_5_v1_to_motor_6_v1: 0
  motor_6_v1_to_endEfector: 0